name: ğŸš€ PR

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [pull_request] # Run only on pull_request, to also get status updates in PRs. We omit push because this would run the steps two times (for push and pull_request).

permissions:
  actions: write
  contents: read
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  lint:
    name: â¬£ Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
      - run: biome ci . --reporter=github

  typecheck:
    name: ğŸ” Type check
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: ğŸ“¥ Download deps
        run: pnpm install

      - name: ğŸ” Type check
        run: pnpm run typecheck

  vitest:
    name: âš¡ Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: ğŸ“¥ Download deps
        run: pnpm install

      - name: âš¡ Run vitest
        run: pnpm run test:cov

  deploy-docs-pr-preview:
    if: ${{ github.event_name == 'pull_request' }}
    name: "ğŸš€ Deploy Docs"
    needs: [lint, typecheck, vitest]
    runs-on: ubuntu-latest
    environment:
      name: docs-release
      url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: forge-42/fly-deploy@v1.0.0-rc.1
        id: deploy
        env:
          FLY_ORG: ${{ vars.FLY_ORG }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_REGION: fra
        with:
          workspace_name: docs
          app_name: react-router-devtools-docs-pr-${{ github.event.number }}
          use_isolated_workspace: true
